version: "3.8"

networks:
  microui:
    driver: bridge

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - microui
    ports:
      - "8080:8080"
    command: ["server"]
    environment:
      PREFIX: "/Users/konstantinnovikov/Source/microui/publish"
      BUILD_TYPE: "Release"
