version: "3.8"

services:
  microui-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microui-server
    ports:
      - "8080:8080"
    command: ["server"]
    environment:
      PREFIX: "/Users/konstantinnovikov/Source/microui/publish"
      BUILD_TYPE: "Release"
